---
LangFile: /etc/locale.conf
DnsConf: /etc/resolv.conf
DockerName: docker-ce-17.09.1.ce
DockerRepo: http://mirrors.aliyun.com/docker-ce/linux/centos/docker-ce.repo
DestRepo: /etc/yum.repos.d/56qq-docker.repo
DockerConf: "[Service]\nExecStart=\nExecStart=/usr/bin/dockerd --live-restore -g /data/docker --insecure-registry docker.56qq.cn:5000 -H 0.0.0.0:2375 -H unix:///var/run/docker.sock"
DockerConfDest: "/etc/systemd/system/docker.service.d/docker.conf"
InstallTool: yum
Logrotate_restart: "/bin/kill -HUP `cat /var/run/syslogd.pid 2> /dev/null` 2> /dev/null || true"
